### ISSUE TITLE
addon does not work,

### ISSUE THREAD

**Issue by pogo1975** [bbsan2k/plugin.video.f1tv#11]
addon throws errors like this:

 ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.f1tv/
2020-02-08 18:06:58.383 T:16792   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
2020-02-08 18:06:59.859 T:15952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'apikey'
                                            Traceback (most recent call last):
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
                                                plugin.run()
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 550, in run
                                                apikey, system_id = _api_manager.account_manager.exteractSessionData()
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\F1TVParser\AccountManager.py", line 34, in exteractSessionData
                                                return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
                                            KeyError: 'apikey'
                                            -->End of Python script error report<--

**Comment by bjorn1981** [comment]
Same error on a clean Libreelec 9.2 install. Either with or without entered credentials in the config.

2020-02-17 14:56:36.373 T:140264801773696   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-02-17 14:56:36.629 T:140262118045440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'apikey'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 502, in run
                                                apikey, system_id = _api_manager.account_manager.exteractSessionData()
                                              File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/AccountManager.py", line 34, in exteractSessionData
                                                return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
                                            KeyError: 'apikey'
                                            -->End of Python script error report<--
2020-02-17 14:56:36.695 T:140264505079552   ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
2020-02-17 14:56:36.711 T:140264801773696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed

**Comment by TheDevFreak** [comment]
I have identified the fix to this issue and will add a pull request in a few minutes.

**Comment by bjorn1981** [comment]
thank you. need testers?
