### ISSUE TITLE
Can't start live sessions due to changed API

### ISSUE THREAD

**Issue by ragnos** [bbsan2k/plugin.video.f1tv#14]
I'm unable to authenticate against F1TV as of now.
I've tried to launch the ongoing preseason testing coverage, but while i could see all kinds of  content as I would expect, i wasn't able to launch the livestream. In an effort to resolve this issue, i've restored the default settings and entered my credentials again. Now i can't even launch the plugin anymore and this is what the logs says about it:

```
2020-02-19 09:44:53.253 T:2224   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: 'apikey'
Traceback (most recent call last):
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
plugin.run()
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 550, in run
apikey, system_id = _api_manager.account_manager.exteractSessionData()
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\F1TVParser\AccountManager.py", line 34, in exteractSessionData
return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
KeyError: 'apikey'
-->End of Python script error report<--
```

I'm able to watch the stream just fine using the website and streamlink.

**Comment by ragnos** [comment]
Follow up: I just missed the PR #13 and tried that code, and while i'm able to start the plugin again, i still can't launch a live stream session. New log:

```
2020-02-19 09:58:21.479 T:11092   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
plugin.run()
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 567, in run
router(sys.argv[2][1:])
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 529, in router
list_content(params['session_url'], params['session_name'])
File "C:\Users\Ragnos\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 377, in list_content
for channel in session['channel_urls']:
TypeError: 'NoneType' object has no attribute '__getitem__'
-->End of Python script error report<--
2020-02-19 09:58:21.503 T:1532   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.f1tv/?action=list_content&session_name=2020%20Pre-Season%20Testing%202020%20Formula%201%20High%20Speed%20Test&session_url=%2fapi%2fsession-occurrence%2fsess_7b0ceaced4c94e50941b2afbda3c19e3%2f
2020-02-19 09:58:21.504 T:11908   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/?action=list_content&session_name=2020%20Pre-Season%20Testing%202020%20Formula%201%20High%20Speed%20Test&session_url=%2fapi%2fsession-occurrence%2fsess_7b0ceaced4c94e50941b2afbda3c19e3%2f) failed
```

I want to add that todays testing session also appears as "High Speed Test", just like the thursday safety car sessions. I wasn't able to launch these type of streams last season aswell, so maybe there is some kind of connection.

**Comment by TheDevFreak** [comment]
@ragnos yep, it seems that f1tv has decided to upgrade, and thusly, completely change the API! Good job it's happened during testing and not just before a race eh? Anyway I'll get working on this later today.

**Comment by theelichtje** [comment]
Thanks for the headsup! Take your time, enjoy some testing for now :)

**Comment by TheDevFreak** [comment]
#18 Resolves this.

I would still like to spend more time on #16 though as at the moment it 'works'
