### ISSUE TITLE
Races from last season do not work (maybe all of archive)

### ISSUE THREAD

**Issue by TheDevFreak** [bbsan2k/plugin.video.f1tv#19]
This will probably be resolved with #16 being completed but it's worth tracking separately anyway

**Comment by bjorn1981** [comment]
I updated the 3 changed files by hand. The 2020 stream for this morning is playable. All archived material throws me this:

2020-02-19 13:47:51.039 T:11764   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'rj' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
                                                plugin.run()
                                              File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 573, in run
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 521, in router
                                                sets()
                                              File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 78, in sets
                                                sets = _api_manager.getSets()
                                              File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\F1TVParser\F1TV_Minimal_API.py", line 130, in getSets
                                                for item in rj['objects'][0]['items']:
                                            UnboundLocalError: local variable 'rj' referenced before assignment
                                            -->End of Python script error report<--

I can test changes on Windows and Librelec if you like. Thanks for the work!

**Comment by TheDevFreak** [comment]
thanks for additional logs; seeing the same thing here on windows. hopefully i can fix it later.

**Comment by TheDevFreak** [comment]
This is fixed as of v0.0.9
