### ISSUE TITLE
Doesn't work on Raspberry Pi with OSMC

### ISSUE THREAD

**Issue by btastic** [bbsan2k/plugin.video.f1tv#2]
Thanks for your work. Unfortunately, this plugin doesn't work on Kodi via OSMC (which is something like Kodi, but not exactly Kodi. Most of the plugins still work though)

Here's the log:

```
23:27:02.767 T:1228927744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 486, in run
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 433, in router
                                                list_seasons()
                                              File "/home/osmc/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 79, in list_seasons
                                                season_list = _api_manager.getSeasons()['objects']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
23:27:02.996 T:1925941760   ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/?action=list_seasons
23:27:02.997 T:1925941760   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/?action=list_seasons) failed
```

I think some error logging would help here.

Thanks

**Comment by bbsan2k** [comment]
Hey,

thanks for your feedback. It looks like there is an issue with your login credentials that I may not have excepted in the python code...
Could you tell me the exact Kodi/OSMC version?
AFAIK OSMC is a distribution like LibreElec/CoreElec that uses Kodi as Frontend..

**Comment by btastic** [comment]
Hey there, it is the latest OSMC version as I always update it when it shows a new version.

Thanks for looking into it!

Btw. The credentials work fine on Kodi for windows.

**Comment by TheDevFreak** [comment]
Closing due to old/inactivity - Ask for a reopen if issue still exists.
