### ISSUE TITLE
Unable to start any video

### ISSUE THREAD

**Issue by ematrix01** [bbsan2k/plugin.video.f1tv#48]
When I try to start something I always receive an error.

Kodi 19.0 on Manjaro Linux.
F1TV-Version: 0.1.4

Logfile:
2021-03-26 23:07:23.407 T:2785     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-03-26 23:07:23.413 T:2785     INFO <general>: PulseAudio: Opened device combined in pcm mode with Buffersize 300 ms Periodsize 100 ms
2021-03-26 23:07:24.671 T:3344     INFO <general>: initializing python engine.
2021-03-26 23:07:24.884 T:3344  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-26 23:07:25.362 T:3344    ERROR <general>: Skipped 2 duplicate messages..
2021-03-26 23:07:25.362 T:3344    ERROR <general>: de
2021-03-26 23:07:25.364 T:3344    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: Invalid paramstring: action=Documentaries!
                                                   Traceback (most recent call last):
                                                     File "/home/bada/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                       plugin.run()
                                                     File "/home/bada/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 656, in run
                                                       router(sys.argv[2][1:])
                                                     File "/home/bada/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 628, in router
                                                       raise ValueError('Invalid paramstring: {0}!'.format(paramstring))
                                                   ValueError: Invalid paramstring: action=Documentaries!
                                                   -->End of Python script error report<--
                                                   
2021-03-26 23:07:25.424 T:3344     INFO <general>: Python interpreter stopped
2021-03-26 23:07:25.435 T:3342    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.f1tv/?action=Documentaries
2021-03-26 23:07:25.436 T:2772    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/?action=Documentaries) failed

**Comment by bbsan2k** [comment]
See https://github.com/bbsan2k/plugin.video.f1tv/issues/44#issuecomment-830780572
