### ISSUE TITLE
Cannot watch any live stream

### ISSUE THREAD

**Issue by joostpielage** [bbsan2k/plugin.video.f1tv#49]
@bbsan2k  thank you so much for your Kodi plugin, I love it so far. I have an issue where I can't watch any live streams. It works well when you want to re-watch something. Any updates on a new release coming? I am running on Kodi 18 and plugin version 1.7

**Comment by bbsan2k** [comment]
Hey,

Please try the latest beta (0.1.99).
This should work on Kodi Matrix! 😊

**Comment by unixseb** [comment]
here's what i get with 0.1.99 in matrix for current live stream :
503 T:6048     INFO <general>: PYF1TV Log: Requested: {"uri": "/CONTENT/PLAY?contentId=1000004214", "target": "PLAY", "name": "LIVE: Pre-Race Show - Portugal"}
2021-05-02 15:01:07.618 T:6048    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'url'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\seb\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
                                                       plugin.run()
                                                     File "C:\Users\seb\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 182, in run
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\seb\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 91, in router
                                                       item = _api.get(params)
                                                     File "C:\Users\seb\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\pyf1tv.py", line 444, in get
                                                       return self.getStreamUrl(item['uri'])
                                                     File "C:\Users\seb\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\pyf1tv.py", line 272, in getStreamUrl
                                                       return content_m3u8_request.json()['resultObj']['url']
                                                   KeyError: 'url'
                                                   -->End of Python script error report<--

**Comment by bbsan2k** [comment]
Please Check 0.1.100

**Comment by unixseb** [comment]
working like a charm, thanks
