### ISSUE TITLE
Add-On won't work on Android

### ISSUE THREAD

**Issue by Fetzii** [bbsan2k/plugin.video.f1tv#55]
I'm trying to run the Add-On on my Fire TV and can't get it running. I tried different Kodi Versions. All Matrix releases can't even be installed and with the Leia releases (ARMv7 and ARMv8) I get an error.

Here is the log:
```
2021-10-24 11:33:32.358 T:16827   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'BLOB'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 530, in run
                                                router(sys.argv[2][1:])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 504, in router
                                                get_mainpage()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 41, in get_mainpage
                                                event_uid = _api_manager.getLiveEvent()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/F1TV_Minimal_API.py", line 134, in getLiveEvent
                                                elements = self.callAPI("home")['objects'][0]['items']
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/F1TV_Minimal_API.py", line 82, in callAPI
                                                return json.loads(cached["blob"])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.cache/lib/cache.py", line 307, in __exit__
                                                self._close()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.cache/lib/cache.py", line 284, in _close
                                                del sqlite3.converters["BLOB"]
                                            KeyError: 'BLOB'
                                            -->End of Python script error report<--
2021-10-24 11:33:32.431 T:16826   ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
2021-10-24 11:33:32.445 T:16741   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
2021-10-24 11:33:35.120 T:8911  NOTICE: CAndroidUtils: Current resolution: 3047x1440 3047x1440 @ 60.000000 - Full Screen
2021-10-24 11:33:36.580 T:16741  NOTICE: Previous line repeats 1 times.
2021-10-24 11:33:36.580 T:16741  NOTICE: CWinSystemAndroid::DestroyWindow
```

**Comment by Seroczynski** [comment]
I have the exact same issue. Tried changing my password but that did not change the outcome.

Using F1TV Kodi Plugin v0.1.7, OSMC running Kodi 18.9 on a Vero 4K+. Fresh F1TV Pro account and first time using this addon. Installed through the repository on Kodi.

**Comment by Seroczynski** [comment]
Little update here. I went ahead and upgraded my Kodi to v19.3 and installed the F1TV Kodi Plugin v0.2.0 and now everything seems to be working fine.

**Comment by bbsan2k** [comment]
This also would have been my recommendation, as older Kodi versions are now unsupported.
